name: Content request
description: Request a new key concept, reference architecture or solution idea for the Power Platform and Copilot Studio Architecture Center
title: "[CONTENT REQUEST]: "
labels: ["request", "triage"]
assignees:
  - manuelap-msft
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting this content request. We triage this feedback regularly and use it to plan for future documentation improvements. Not all content requests are implemented, but we'll prioritize based on current work priorities and the tooling available.
  - type: textarea
    id: description
    attributes:
      label: Describe the type of key concept, reference architecture or solution idea for the Power Platform and Copilot Studio Architecture Center
      description: Also, tell us what you expected to see?
      placeholder: Tell us what you want to see!
    validations:
      required: true  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
